/*
-- Query: SELECT * FROM 557_final_project.pi_campus
LIMIT 0, 1000

-- Date: 2022-05-06 09:14
*/
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (1,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (2,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (3,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (4,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (5,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (6,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (7,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (8,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (9,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (10,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (11,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (12,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (13,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (14,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (15,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (16,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (17,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (18,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (19,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (20,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (21,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (22,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (23,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (24,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (25,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (26,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (27,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (28,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (29,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (30,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (31,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (32,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (33,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (34,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (35,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (36,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (37,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (38,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (39,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (40,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (41,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (42,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (43,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (44,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (45,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (46,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (47,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (48,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (49,1);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (50,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (51,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (52,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (53,2);
INSERT INTO `` (`PI_ID`,`Campus_ID`) VALUES (54,2);
