/*
-- Query: SELECT * FROM 557_final_project.pi_postdoc
LIMIT 0, 1000

-- Date: 2022-05-06 09:14
*/
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (1,1);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (2,2);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (3,2);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (5,3);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (6,4);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (7,4);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (8,4);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (9,6);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (10,7);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (13,10);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (15,11);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (16,13);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (17,13);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (19,16);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (20,16);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (21,20);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (22,21);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (23,21);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (25,24);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (26,24);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (27,25);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (28,25);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (29,26);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (30,26);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (31,26);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (33,27);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (34,28);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (35,29);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (36,30);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (37,31);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (38,33);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (39,35);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (40,37);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (41,45);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (42,47);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (43,47);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (44,48);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (45,48);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (46,49);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (47,49);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (48,50);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (49,52);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (50,52);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (51,52);
INSERT INTO `` (`Phd_ID`,`PI_ID`) VALUES (52,52);
